# Generated by Django 5.1.7 on 2025-03-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_posts_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-time_create"]},
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-time_create"], name="blog_post_time_cr_cc1db6_idx"
            ),
        ),
    ]
