# Generated by Django 5.1.7 on 2025-03-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_post_blog_post_time_cr_cc1db6_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
