# Generated by Django 5.1.7 on 2025-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(default="slug", max_length=255),
        ),
    ]
