# Generated by Django 5.1.7 on 2025-03-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=255, unique=True),
                ),
                ("summury", models.TextField(max_length=255)),
                ("content", models.TextField()),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                ("author", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["-time_create"],
                "indexes": [
                    models.Index(
                        fields=["-time_create"],
                        name="posts_post_time_cr_e5aa17_idx",
                    )
                ],
            },
        ),
    ]
