# Generated by Django 5.1.7 on 2025-03-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderBIO",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="posts.post",
                    ),
                ),
            ],
            bases=("posts.post",),
        ),
    ]
