# Generated by Django 5.1.7 on 2025-03-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_founderbio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FounderBIO",
        ),
    ]
