# Generated by Django 5.1.7 on 2025-03-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_category_post_cat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="posts.category",
            ),
        ),
    ]
