# Generated by Django 5.1.7 on 2025-03-29 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_tagpost_alter_post_options_alter_post_cat_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("count_publish", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="co_author",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="author",
                to="posts.author",
            ),
        ),
    ]
