# Generated by Django 5.1.7 on 2025-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_author_post_co_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="citation_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
