# Generated by Django 4.2.20 on 2025-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_alter_author_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="co_author",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Пост"),
        ),
        migrations.AlterField(
            model_name="post",
            name="summury",
            field=models.TextField(
                max_length=255, verbose_name="Краткое содержание"
            ),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
