# Generated by Django 4.2.20 on 2025-06-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_remove_post_co_author_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/files/%Y/%m/%d/",
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="Тэг",
                to="posts.tagpost",
                verbose_name="Тэги",
            ),
        ),
    ]
