# Generated by Django 4.2.20 on 2025-06-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_post_file_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Файл"
            ),
        ),
    ]
