# Generated by Django 4.2.20 on 2025-06-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0013_alter_post_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="files/%Y/%m/%d/",
                verbose_name="Файл",
            ),
        ),
    ]
