# Generated by Django 4.2.20 on 2025-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0014_alter_post_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/%Y/%m/%d/",
                verbose_name="Изображение",
            ),
        ),
    ]
